### ISSUE TITLE
SFX/music playback completely broken after latest changes

### ISSUE THREAD

**Issue by DPS2004** [jtothebell/fake-08#110]
Certain music channels seem to not be playing at all, with a quiet "pop" sound being played instead.
[musictest.zip](https://github.com/jtothebell/fake-08/files/8226232/musictest.zip)
I made a test cart to showcase the various issues I have found. It might be a good decision to revert the sfx changes, as they seem to break more than they fix.

**Comment by jtothebell** [comment]
Closing this since the change that caused the problem has been reverted
