### ISSUE TITLE
3DS suggestion: 800px mode support

### ISSUE THREAD

**Issue by DPS2004** [jtothebell/fake-08#111]
![800px](https://user-images.githubusercontent.com/10176105/159142654-960e711b-bcd8-47b8-96ad-eca9be3724a3.png)
since the display of the 3ds is actually 800x240, with rectangular pixels, [libtru has a function](https://libctru.devkitpro.org/gfx_8h.html#a1ffe33f6b3e9a61ee916997fc6cf6ace) that makes the top screen render an image of that size, instead of the regular 400x240 with square pixels.

[example implementation](https://github.com/RocketRobz/HoriHD-Gallery/blob/master/source/main.cpp#L53)

**Comment by jtothebell** [comment]
This seems to be a pretty straightforward change that definitely improves the quality of the non-integer scaled modes on the top screen. Put together a quick PR for this
