### ISSUE TITLE
Bittboy/PowKiddy V90 - cropped pixels in 1:1 scale: Add 240x240 renderingmode

### ISSUE THREAD

**Issue by SirMuddyhood** [jtothebell/fake-08#115]
1:1 scale on a PowKiddy V90 (320 x 240) screen crops several rows on both the top and bottom of the screen. Horrifying, potato-quality photos of full screen and 1:1 scaling below for reference:

![PXL_20220323_145441642](https://user-images.githubusercontent.com/5615693/159731230-319d75e9-b7d5-49fa-be48-67ec552cb088.jpg)

![PXL_20220323_145429292](https://user-images.githubusercontent.com/5615693/159731233-69b3fc03-fc82-413d-9cc7-8cb29a13284d.jpg)

FAKE-08 v0.0.2.16 / MiyooCFW v1.3.3

**Comment by jtothebell** [comment]
This is by design to keep the pixels nice and square, but I guess some people might prefer a square aspect ratio that fits in the screen. Personally, I think that stretching 128 pixels to 240 looks awful, but I should be able to add it for those that prefer that.

**Comment by SirMuddyhood** [comment]
> 

I totally understand the rationale, and I'm sure that works perfectly well for the vast majority of carts out there. Surely not one to prioritize straight away, but a stretched 1:1 to cover edge cases with prominent top or bottom UI elements would be terrific when time allows!

**Comment by jtothebell** [comment]
Latest release has this mode added in

**Comment by SirMuddyhood** [comment]
I got the notification email for the new release and literally dropped everything to try it - it works perfectly and looks great! So, so appreciative of the update.
