### ISSUE TITLE
No sound with 3DS/2DS

### ISSUE THREAD

**Issue by colibris79** [jtothebell/fake-08#123]
Hi, I've tried the last two releases with my old 3ds and new 2ds xl and none of them has sound at all. Is working great with my Miyoo Mini though. Do I have to change anything or is this normal?
Thanks for this amazing version of Pico-8

**Comment by jtothebell** [comment]
I'm not near a 3DS to check right now, but I'm fairly sure the audio is working in the latest release. Does other 3DS homebrew audio work? My first guess is that you didn't dump your DSP firmware or something went wrong in the process: https://3ds.hacks.guide/finalizing-setup

**Comment by colibris79** [comment]
Was as simple as that. It had been ages since I had done the homebrew process and I thought I had done everything. Sorry and thanks for taking your time to answer such a basic question
