### ISSUE TITLE
poke() support?

### ISSUE THREAD

**Issue by calbatr0ss** [jtothebell/fake-08#129]
Not sure but I suspect this is because of missing poke() support — [Yolo Solo](https://www.lexaloffle.com/bbs/?tid=39254) won’t load anything visually, only the audio loads. This cart uses poke() to set the display to 64x64 resolution as it was part of the lowrezjam.

**Comment by DPS2004** [comment]
FAKE-08 does have poke() support, and I have tested other carts that use the 64x64 mode that work well, so the issue is probably something else. What platform are you using?

**Comment by jtothebell** [comment]
There is poke support, and it should support 64x64 mode as well. I know at least a few games work that use that mode. I can take a closer look at yolo solo sometime in the next few days to hopefully narrow down what the problem is.

**Comment by jtothebell** [comment]
@calbatr0ss do you have any more information on this? I tried on couple different platforms and everything seemed to be working.

**Comment by calbatr0ss** [comment]
@jtothebell thanks for taking a look, I’m testing on the Miyoo Mini v1 with the latest firmware and Onion OS 3.10.6

**Comment by calbatr0ss** [comment]
Tested on a fresh install, still no luck. Also having similar issues with the cart Golf Sunday. Celeste and Celeste 2 carts work as expected...

Here's an pic of what I'm seeing in Yolo Solo. I can hear the audio just fine but the picture is black and when I press pause I can only see a fraction of the menu. ![image](https://user-images.githubusercontent.com/20192836/171323440-c27cc62e-0bef-49a0-9f1a-c8ebd8578e68.jpeg)

**Comment by DPS2004** [comment]
hm, it almost looks like its zoomed in on the wrong corner of the display?

**Comment by calbatr0ss** [comment]
That's kind of what it looks like, but I didn't think the pause menu was zoomed at all in 64x64 mode

**Comment by jtothebell** [comment]
Ah, that screenshot is a good clue. I suspect it's showing the wrong corner of the screen because the Miyoo mini screen buffer is upside down.

**Comment by jtothebell** [comment]
This build should fix it! You'll need to replace `FAKE08` in emus/PICO with this one
[MiyooMini.zip](https://github.com/jtothebell/fake-08/files/8819979/MiyooMini.zip)

It looks like there are some minor graphical glitches that we'll also need to take a look at, but it is playable now (but also hard. Or I need to git gud)

**Comment by calbatr0ss** [comment]
Tested and working (aside from those graphical glitches), thanks so much! (and hope you enjoy the game!)

**Comment by jtothebell** [comment]
Great. Closing this issue and will open a new one for the graphical issues.
