### ISSUE TITLE
.cia build

### ISSUE THREAD

**Issue by DrPickens** [jtothebell/fake-08#13]
I have CFW on my 3DS, so i prefer .cia to .3dsx as a file format

**Comment by jtothebell** [comment]
Thanks for creating this issue. This has been in the back of my mind but I’ve been focusing on other things, but it probably makes sense to do it soon. Looks like it shouldn’t be too much trouble, so I might be able to do it this weekend. 

Leaving this link here for reference on how to do it: https://darkwebcrypt.blogspot.com/2020/04/dungeons-of-daggorath-3ds-making-release.html?m=1

**Comment by jtothebell** [comment]
@DrPickens I've updated the latest pre-release version to have a CIA binary in the 3ds zip. Seems to work for me, but if you want to check it out, that would be great.

**Comment by DrPickens** [comment]
Works!
