### ISSUE TITLE
Miyoo Mini: Loading "Barp the Balldragon" crashes the system

### ISSUE THREAD

**Issue by tarikalmashni** [jtothebell/fake-08#135]
Of all the PICO-8 games, "Barp the Balldragon" (https://www.lexaloffle.com/bbs/?pid=54396) is my favorite and while it works on other systems with FAKE-08 (for example the Nintendo Switch) it crashes the Miyoo Mini.
All other games I've tested so far seem to look fine.
Launching it shows the "LOADING" screen of the Miyoo Mini but not even the three dots underneath (aka the loading animation) appear but it freezes completely so I have to force shutdown with START+SELECT+L2+R2.

Please let me know if I can help you hunt that error down by testing with some kind of debug build that creates logs on the SD card.

**Comment by jtothebell** [comment]
Thank you for the report. I confirmed that I see the same behavior on my mini, but Barp works on the other platform I tested. That makes it tricky to debug but I'll dig in some more soon and let you know if I need any other info.

**Comment by tarikalmashni** [comment]
So meanwhile you've got your own Mini as well, great.
Thanks!

**Comment by jtothebell** [comment]
It looks like aggressive compiler optimizations are leading to an infinite loop. I'm hoping to find a fix to allow the optimizations to remain turned on, but in the mean time, here is a build with optimizations turned down where Barp seems to work (taken from this branch if you care to see the flag change: https://github.com/jtothebell/fake-08/tree/BarpMiyooMini) [MiyooMini-NoOptim.zip](https://github.com/jtothebell/fake-08/files/8934584/MiyooMini-NoOptim.zip)

**Comment by tarikalmashni** [comment]
Interesting. Thanks for the custom build and of course your time and effort! It's indeed working now on my end too! =)
