### ISSUE TITLE
3DS: issue loading a game

### ISSUE THREAD

**Issue by RandomMan25XX** [jtothebell/fake-08#146]
I recently bought Nog Arcade (https://ryancavendell.itch.io/nog-arcade) as part of a recent bundle and decided to try it with fake-08 only to get this error after trying to load it (see attached screenshot, screenshot isnt the best as direct capture of apps that use 800px mode get stretched to one side of the screen)
![20220708_020214](https://user-images.githubusercontent.com/13063346/177958448-d1b8b408-e702-4120-8e9b-5591a0560f03.jpg)

**Comment by nckstwrt** [comment]
This is an error I will try and help and fix - but is with the lua parser.
The line it's failing on is:
		for j=0,3do if(btn(j,p[4]))p[2]=j+1end
(in your .p8 file it will be line 544)

If you just put a space before the "end" so it reads:
		for j=0,3do if(btn(j,p[4]))p[2]=j+1 end

It will work.

**Comment by nckstwrt** [comment]
PICO-8 does not seem to support numbers with an exponent (so 4.5e+6 or similar). Lua does however, so in the function read_numeral in llex.c you have:

  const char *expo = "Ee";
  ...
    if (check_next(ls, expo))  /* exponent part? */
      check_next(ls, "+-");  /* optional exponent sign */
etc

I think those 3 lines can be removed and then carts where they are bunching up the "end" keyword next to numbers (to save space) will work without modification.

**Comment by jtothebell** [comment]
Fix as described has been pushed to master. I should be pushing a new release soon, but you can also grab the latest build from the Actions section if you would like to.

**Comment by RandomMan25XX** [comment]
> Fix as described has been pushed to master. I should be pushing a new release soon, but you can also grab the latest build from the Actions section if you would like to.

Compiled the latest commit and now the game works fine (except for the minigame that requires a keyboard, making that two games I know uses the keyboard in some capacity)
