### ISSUE TITLE
Custom fonts not supported

### ISSUE THREAD

**Issue by Rezzy-dev** [jtothebell/fake-08#154]
Numbers are not sampled correctly from the font palette by Fake-08 in Pico World Race. When the race starts and ends, you can see garbled characters where the numbers should be: "1st", "2nd", etc.

![Pico World Race p8](https://user-images.githubusercontent.com/4543835/179354645-2bcf3179-c72c-444c-a05c-c968b13d8908.png)

**Comment by jtothebell** [comment]
It looks like that cart uses a custom font, which is not yet supported by FAKE-08

**Comment by Rezzy-dev** [comment]
Ah, that makes sense! :D I guess this game is using the default font for some of the text, and a custom font (or two) for other texts. Thanks! :+1:
