### ISSUE TITLE
Add an alternative graphical interface to navigate and choose games 

### ISSUE THREAD

**Issue by badjuice** [jtothebell/fake-08#158]
Currently I have more than 100 games on my folder.

To make it easier to navigate these games other than the already implemented "skip 1" or "skip 10" games while also only seeing one name at a time, a different approach that I would recommend is to maybe add another way to visualize the games that are on your folder such as a list. This could (or not) include the game's preview image (like in splore) but really a list is all that I am really asking for on this issue, just to keep things simple. It would be a game changer.

**Comment by DPS2004** [comment]
have you tried the alternate menu modes in the settings menu?

**Comment by jtothebell** [comment]
As pointed out, DPS2004 recently added two alternate interfaces, one of which is a list very similar to the splore interface. For me personally, the UI is not a focus currently. I'd be willing to consider further PR's that enhance the UI, but I'm going to close this issue as there isn't anything directly actionable.

**Comment by badjuice** [comment]
> have you tried the alternate menu modes in the settings menu?

I don't think I did. Did not see that mentioned anywhere. How can I access the settings menu/alternate menu mod?
