### ISSUE TITLE
Trying to build on Odroid C4 fails

### ISSUE THREAD

**Issue by vanfanel** [jtothebell/fake-08#161]
Hi,

I run Debian 11 on this board, and I see this when trying to do an SDL2 build:

```
In file included from /home/manuel/src/fake-08/platform/SDL2Desktop/../../source/cart.h:5,
                 from /home/manuel/src/fake-08/platform/SDL2Desktop/../../source/cart.cpp:12:
/home/manuel/src/fake-08/platform/SDL2Desktop/../../source/graphics.h:7:10: fatal error: fix32.h: No such file or directory
    7 | #include <fix32.h>
      |          ^~~~~~~~~

```

Same happens on x86_64. Any idea on what's going on?? Thanks!

**Comment by jtothebell** [comment]
That looks like you didn't clone the submodules along with the base repo: https://stackoverflow.com/a/4438292

**Comment by vanfanel** [comment]
@jtothebell Ah! That was it!

BTW, have you considered a libretro port? These games look gorgeous with CRT-like shaders!

**Comment by vanfanel** [comment]
That's fantastic, @jtothebell 
I will try it ASAP! I have several licenses of Pico8, but having shaders totally makes them unusable with this :D

**Comment by vanfanel** [comment]
Hm, tried the libretro port, seems to fail linking on the C4...

```
/usr/bin/ld: cannot open linker script file ../../link.T: No such file or directory
collect2: error: ld returned 1 exit status
```
