### ISSUE TITLE
Double buffering side effect on Miyoo Mini

### ISSUE THREAD

**Issue by schmurtzm** [jtothebell/fake-08#167]
Hi,

[Activation of double buffering](https://github.com/jtothebell/fake-08/issues/153) has a great effect on tearing on Miyoo Mini but it triggers a side effect : there are flickering glitches on the black borders of the screen as in this video :
[youtu.be/l9j1t2ZZMm4](https://youtu.be/l9j1t2ZZMm4)

To reproduce : build last dev build from main branch then press "select" to change display stretch mode when something is moving in the game.

Probably something like the requirement of a blit when a change of display stretch mode has been done ?

(I create a dedicated issue outside the #153 for better visibility)

Thanks.

**Comment by jtothebell** [comment]
I think I have a fix for this. It looks like the second buffer doesn't get cleared by the Miyoo Mini SDL (can't repro on a desktop build) so I added a screen clear before flipping, and it seems to have resolved it. There is probably a small performance cost for that, but it didn't seem to be noticable in the few games I tested
https://github.com/jtothebell/fake-08/actions/runs/3071232350

**Comment by schmurtzm** [comment]
Seems to work well, I'll make some tests with the community and after that we can close I think :)
Thanks for your great support !
