### ISSUE TITLE
POOM Miyoo Mini

### ISSUE THREAD

**Issue by bigmonkeynads** [jtothebell/fake-08#168]
So I assume it’s the emulator handling POOM. The weapon wheel when you bring it up with the start button on the Miyoo you then choose what weapon you want by pressing the dpad direction once pressed it shows the other weapon but straight away retracts and brings back the shotgun by default no matter what you do. POOM weapon wheel works on many other devices just for some reason it’s like a bug on the Miyoo Mini emulator

**Comment by jtothebell** [comment]
What version are you running? That should be fixed in version [v0.0.2.18](https://github.com/jtothebell/fake-08/tree/v0.0.2.18)

**Comment by bigmonkeynads** [comment]
Oh? I updated to the latest Onion V4.0.1 but perhaps the Fake08 emulator hasn’t updated? That’s awesome to know thanks for the response I’ll look for the latest version! Thanks heaps

**Comment by bigmonkeynads** [comment]
Oh do I just replace the .elf from that latest release?

**Comment by bigmonkeynads** [comment]
Sorted, because I had POOM in its own emulator folder it missed being overwritten/updated when moving to Onion v4. I copied Fake08 over it and it’s now sorted thanks
