### ISSUE TITLE
srand and music bugs

### ISSUE THREAD

**Issue by SuperPositiveP** [jtothebell/fake-08#17]
Doing srand() without providing a seed throws an error in fake-08 despite working fine in PICO-8. Can be worked around by giving srand a seed of 0 as in srand(0). Both probably do the same thing in PICO-8, but it is still incorrect behavior for srand() to not work. Can probably be fixed by making the seed an optional argument that defaults to zero when no argument is provided.

music(-1) is incorrectly interpreted as music(0) by fake-08. music(-1) is supposed to terminate any music that this currently playing.

Finally, and I know this is a 0.2 feature but I will mention it anyway, rnd() throws an error when given a table. Can be worked around using the trick that was used to get random choices from tables prior to 0.2.

**Comment by SuperPositiveP** [comment]
Alternatively, you could patch every srand() in carts into srand(0), but that is a bit of a silly solution.

**Comment by jtothebell** [comment]
Thank you for the report. I think the srand bug should be a pretty easy fix. I'm not sure about music though, I thought passing -1 would terminate the music. Unfortunately I probably can't look into either bug until middle of next week, but I will as soon as I can.

**Comment by jtothebell** [comment]
Sorry for taking longer than I estimated, but I've just pushed fixes for srand()'s default argument and music(-1) not stopping the music. I added new binaries to the latest pre-release, or you can pull the code and build yourself. I also added mention of passing a table to rnd() in the 0.2 features ticket (#6)
