### ISSUE TITLE
Android frontend support 

### ISSUE THREAD

**Issue by guillaumevidal** [jtothebell/fake-08#176]
Hello, 

The Android libretro core seem to work well. 
However, i can't seem to run carts from a frontend. Launching from RA is OK, but launching from Daijisho shows the cart in a cart selector menu, not launching it. And i can't seem to find a way to launch the game from that. 

I haven't been able to add the .info file to the core folder, as changing the core folder from the default makes me unable to run the core, and default folder is not accessible without root. 

I'm using the 64 bit RA core on a Oneplus 7T. Will try some other devices soon.

**Comment by sunydo** [comment]
I'm done with this problem
Change the game png suffix to p8
@guillaumevidal
perfect

**Comment by jtothebell** [comment]
The latest release has a fix that helps in some situtations, and I've also added some instructions to the wiki that are working on the couple devices I have to test with: https://github.com/jtothebell/fake-08/wiki/Android-Libretro-Instructions
