### ISSUE TITLE
btn() and btnp() do not accept emojis as arguments

### ISSUE THREAD

**Issue by redorka** [jtothebell/fake-08#18]
In PICO-8, btn() and btnp() functions can accept emojis(such as ⬅️ and ➡️) (NOT STRING) as argument for what input to read. However, in FAKE-08, these presented in arguments return "unexpected symbol" error and do not allow running the cart.
[cart+log.zip](https://github.com/jtothebell/fake-08/files/5142508/cart%2Blog.zip)
(Tested on New 3DS XL via CIA prebuild in release)

Possible solution: make gamepad emojis into global variables like here
![image](https://user-images.githubusercontent.com/47483536/91578759-4eb0fa00-e953-11ea-96b9-7f9d5065bfab.png)

**Comment by jtothebell** [comment]
I think I have this addressed via PR #19. I'm attaching a 3dsx build here if you want to give it a try
[FAKE-08.3dsx.zip](https://github.com/jtothebell/fake-08/files/5146308/FAKE-08.3dsx.zip)

**Comment by jtothebell** [comment]
Never heard back. Did a bit more testing, and seems to be working. Merging PR and closing issue.
