### ISSUE TITLE
Miyoo Mini: Error loading cart lua / No lua to load

### ISSUE THREAD

**Issue by allengaleana** [jtothebell/fake-08#180]
Hello. I have been unable to start two games on the Miyoo Mini V2: _Contra Demake_ and _Aztec_.

In the case of the first one, I get the message **>error loading cart lua: [string "--contra concept ..."]:**

In the case of the second one, I get the message **>no lua to load. Aborting cart**

Do you know why this is happening and how to fix it?

**Comment by allengaleana** [comment]
And by the way, I have the latest version of Onion OS (4.3, I think).

**Comment by TotallyNotSethP** [comment]
I'm having the same issue with Terra
