### ISSUE TITLE
Allow us to configure mouse input to the gamepad

### ISSUE THREAD

**Issue by medeirosT** [jtothebell/fake-08#187]
Hello Fake-08!

I've noticed that for pico-08 games that require a mouse, there is no support for retroarch mouse-less/touchscreen-less devices.

For our SBC devices (Such as the Anbernic RG351/RG552/RG353 series) we've started using a patch that goes around this by directly mapping the controller, but proper support would be nice. 

I'm including our patch (It's a quick and dirty hack, but it does a basic job of allowing our users to at least use the left mouse button) hoping it helps in any way!

Thank you for your hard work!

[0001-analog-to-mouse.patch.txt](https://github.com/jtothebell/fake-08/files/10756843/0001-analog-to-mouse.patch.txt)

**Comment by jtothebell** [comment]
Hello @medeirosT! I just pushed an update that should make your patch unnecessary. I don't have a build set up to test on one of the devices you mentioned, but it seemed to be working on my retroid pocket 2 (an Android device with an analog stick but no touch screen). Let me know if you see any issues with it.

**Comment by jtothebell** [comment]
The latest release has this fix in it. If there are any issues, you can comment here to re-open or make a new issue.
