### ISSUE TITLE
Is there a way to type KEYCONFIG or otherwise rebind on the 3DS?

### ISSUE THREAD

**Issue by JonathanDotCel** [jtothebell/fake-08#197]
With the physical matching layout (e.g. B/O/bottom left, A/X/top right) some games are harder than they ought to be, and other times it just sort of kills the fun.

E.g. in celeste, holding X to cling, then tapping O to jump can result in accidental releases, since your thumb goes up through the buttons at 90 degrees, rather than naturally along them (as it would with the standard platformer Y/B layout).

Less of an issue on e.g. the Gameboy, since the buttons weren't a at 45 degrees in a diamond shape, but it would be fantastic if we could do something about it here.

If there's nothing in the works, would you accept a PR along these lines?

Thanks.

**Comment by jtothebell** [comment]
I don't currently have anything in the works, though this is a feature that I would like to have. Ideally buttons could be remapped and their mappings stored in the settings.ini file, and maybe even change the mappings in the settings dialog. Another option would be adding a "swap buttons" option to the pause dialog. I don't anticipate getting around to this any time soon, but if you'd like to take a look I would definitely look at the PR.
