### ISSUE TITLE
Support data.pod

### ISSUE THREAD

**Issue by diimdeep** [jtothebell/fake-08#199]
Many games distributed without cart.p8, but only converted to platforms that each contains the same `data.pod` file. If it is possible, support loading this file.

**Comment by jtothebell** [comment]
While it may be possible, I don't really want to try to reverse engineer that format. Usually when someone chooses to distribute their game as a standalone executable and not a cart, they have a reason why. I don't want to rule it out completely, but I've slowed down work significantly and will not get to this any time soon, so I'm going to close this issue.
