### ISSUE TITLE
png files and the retroarch core

### ISSUE THREAD

**Issue by christianhaitian** [jtothebell/fake-08#200]
Hi,

The retroarch core doesn't load pico-8 games that have the ending extension of .png.  Per this PR (https://github.com/jtothebell/fake-08/pull/12), this was addressed back in 2020 and while png files work fine with the standalone core, they don't with the retroarch core.  As an example, try this celeste game <https://www.lexaloffle.com/bbs/cposts/1/15133.p8.png> or Scrapboy <https://www.lexaloffle.com/bbs/cposts/sc/scrap_boy-6.p8.png> from lexaloffel. 

For the now the issue can be worked around by renaming the .png files to .p8.

**Comment by jtothebell** [comment]
Do you have any more info about what is not working and on what platform? Png carts are working with the libretro core on Android and Miyoo Mini, and I just confirmed that those linked carts work just fine with a local build on my machine.

The only issue I've run into with png carts is in retroarch the built in image viewer can take precedence over the core if it isn't disabled (Retroarch ­­> Configurations > File Browser > Use Built-In Image Viewer)

**Comment by christianhaitian** [comment]
Oh wow, that's exactly the issue. Thanks for the tip on this.

For completeness, this was on an aarch64 platform (RK3326 and RK3566 devices using ArkOS or JelOS with Retroarch 1.15)

Thanks again
