### ISSUE TITLE
"No carts found"

### ISSUE THREAD

**Issue by lyvaviv** [jtothebell/fake-08#201]
I put all my .p8.png files in the p8carts folder at the root of my SD card. But when I open fake-08 (o3DS, CIA install) it just says "no carts found".

**Comment by ShadowDrakken** [comment]
I know for OnionOS it needs to be in "\ROMS\PICO\" even though the error says "\p8carts\". Does the OS you're using also have an alternate location?

**Comment by GK-GreyGhost** [comment]
I'm having the same problem, I've tried /ROMS/PICO, /roms/pico-8, /p8carts with both .p8 text files and .p8.png files, latest version with GarlicOS / Anbernic rg35xx
