### ISSUE TITLE
Can't change controls in retroarch core

### ISSUE THREAD

**Issue by christianhaitian** [jtothebell/fake-08#202]
Hi,

The retroarch core doesn't allow the ability to change default controls on a aarch64 build.  Only option to change the controls is via the retroarch global controls which changes it for multiple cores instead of the one.

Thanks,

**Comment by jtothebell** [comment]
I just pushed a change (df31feb) that I think addresses this issue. I can now remap the controls in the quick menu, whereas before I couldn't. Let me know if I misunderstood or there is any other problem.

**Comment by mend13ta** [comment]
Sorry but i don't have the environment (and knowledge) to compile with this patch, would you be gentle to upload this on releases?
