### ISSUE TITLE
Count function doesn't work

### ISSUE THREAD

**Issue by Godmil** [jtothebell/fake-08#203]
The pico8 function ```count(table,value)``` which is supposed to return the number of values found in the table instead returns the size of the table.
This code:
``` lua
count({"one","two","three"}, "ten")
count({"one","two","three"}, "two")
```
on pico8 returns 0,1  but in fake08 it returns 3,3

Tested on OnionOS v4.2.0 beta on Miyoo Mini+

**Comment by jtothebell** [comment]
This is fixed via PR #204 . Thank you again!
