### ISSUE TITLE
sfx() with channel -2 to stop sound not working

### ISSUE THREAD

**Issue by rikimbo** [jtothebell/fake-08#206]
Calling `sfx()` with the [channel] argument set to `-2` should interrupt (stop) a given sound from playing on any channels it's playing on. I noticed that isn't working properly in this cart: [Pico Joust 2600](https://www.lexaloffle.com/bbs/?tid=50964)

In the linked cart, you can notice the effect when you die and respawn. There's a sound that plays for a long time, increasing up in frequency. It's supposed to be interrupted when you start moving again, with a call to `sfx(6,-2)` in the code. Instead, it plays for its full duration.

**Comment by jtothebell** [comment]
Thank you for the detailed report. I've just pushed a fix for it, and it will be included in the next release (I'm not sure when that will be)

**Comment by rikimbo** [comment]
I downloaded the artifacts from commit https://github.com/jtothebell/fake-08/commit/aebd6b9648d1c450910ad79c78f9280dfbd20b25 and tried it out on Android (RG405m) with the cart I linked above. Seems to work well!

I'm not sure if you normally wait until a release before closing the issue, but as far as I can tell, this is resolved. Thanks so much!
