### ISSUE TITLE
Regressions in print

### ISSUE THREAD

**Issue by DPS2004** [jtothebell/fake-08#217]
In recent versions of FAKE-08 `print` has been behaving unexpectedly. To be specific:
- double-width characters (notably P8SCII symbols) only take up a single space
- certain palette modifying actions, as seen in test/carts/boldtexttest.p8, cause the text to render incorrectly

I've narrowed down the double-width error to first occuring starting with [this commit](https://github.com/jtothebell/fake-08/commit/6d9954ba5a433159191d111e3b1a6340530448fa), and the palette bug starting with [this commit.](https://github.com/jtothebell/fake-08/commit/4c901913301a7e05618c2c9a0ab0b9126a198214)

Expected behavior:
![image](https://github.com/jtothebell/fake-08/assets/10176105/0b9ce573-d5be-4bf2-aa12-f398d9e68468)
Current behavior:
![image](https://github.com/jtothebell/fake-08/assets/10176105/aaa37ff2-ddf0-4f3c-aa29-ae4cb0a7f177)

Sorry if this was already known about, but I couldn't find an issue about it.

**Comment by jtothebell** [comment]
Thanks for reporting, I was not aware of these regressions. Those two cases should be fixed on master now. Hopefully there aren't any other regressions. 

Side note, I find it hilarious that one of the repro cases was already in the test repo, but just wasn't wired up. While fixing this I put a bit of time into making those e2e tests not need to be manually wired up, but just pick up new carts/screenshots so hopefully that won't happen again after I finish that up.
