### ISSUE TITLE
X6 Compatibility

### ISSUE THREAD

**Issue by PedroLucas201441** [jtothebell/fake-08#227]
You can make a version compatible with x6

**Comment by DPS2004** [comment]
Is x6 the name of a game or a device?

**Comment by PedroLucas201441** [comment]
a device
![image](https://github.com/jtothebell/fake-08/assets/118313199/4bfc9fdc-bf8a-4cd2-b291-6fbbd26e1910)

**Comment by jtothebell** [comment]
Based on a quick google search, it looks like it is very underpowered and struggles with SNES emulation, so it is probably not a good candidate for Pico-8 emulation. I also don't see a toolchain available to build with. If anyone else knows of a way and would like to submit a PR, that is fine, but I won't be purchasing one or porting to it.

**Comment by PedroLucas201441** [comment]
but an guy have a custom firmware or a retroarch for this console send me
