### ISSUE TITLE
[libretro] distribute via RetroArch's online updater?

### ISSUE THREAD

**Issue by hizzlekizzle** [jtothebell/fake-08#232]
Hi there, I'm involved in RetroArch/libretro and we wondered if you all were interested in having this emulator/core available for users to download from our in-app core downloader? If so, we have a few options to make it happen.

The most straightforward way would be to add a [gitlab CI recipe](https://github.com/libretro/snes9x/blob/master/.gitlab-ci.yml) to the top level of your repo and we'll clone, build and distribute it from our servers.

If that's undesirable for whatever reason (e.g., CI recipe conflicts or whatever), we can work something else out, like a super-shallow fork that just adds the recipe alongside your repo as a submodule, etc.

Any thoughts?

The only other thing we'd need is the core info file added to our libretro-super repo, but it looks like it's already there.

**Comment by jtothebell** [comment]
Hello, and thank you for your interest. I would eventually like to include the core in the in app downloader, but I've been holding off for a couple reasons. The first is that I've been (very) slowly working on an update that will break save state compatibility with old versions. The second is that I don't want to discourage people from purchasing a Pico-8 license. In a brief exchange I had with Zep (the Pico-8 author) he said he appreciated that I wasn't distributing Fake-08 on platforms where Pico-8 was available, but that wouldn't be necessary after Pico-8 hits 1.0 and the API is solidified. He said he is "a little anxious about the unpredictable dynamics of opensource emulators becoming popular before I get a chance to finish and release it myself," and I would like to respect that.

**Comment by hizzlekizzle** [comment]
Ah, yeah, those are good reasons, and we'll respect them, as well.

If when those blocks are cleared, just give me a ping and we can get it going.

**Comment by jtothebell** [comment]
Thank you, hopefully I'll be in touch in the not too distant future.
