### ISSUE TITLE
Blue(12) color displays as black + some shapes aren't drawn + map() doesn't work when not all arguments provided

### ISSUE THREAD

**Issue by redorka** [jtothebell/fake-08#29]
**Issues encountered in:** Iceberg Curse
![icecur p8](https://user-images.githubusercontent.com/47483536/101241747-f46dc500-3709-11eb-95db-8778212431ad.png)
**Version:** 3DS CIA build v0.0.2

As I was trying to debug with other carts I couldn't find the exact why first 2 issues happen as other carts work fine (Pico De Pon as example) but blue color (12) is displayed as black instead as well as some shapes not being drawn in that particular cart. map() not displaying when not all arguments provided seems to be consistent though?

(Sorry for throwing several issues in one but i was too lazy to post each one separately)

**Comment by jtothebell** [comment]
Thanks for the report! Just published a new release the should address the three issues preventing that cart from being playable. Its still not 100% compatibility because fillp() support isn't there, but it should be working now.
