### ISSUE TITLE
Add QR code for cia

### ISSUE THREAD

**Issue by Archonic944** [jtothebell/fake-08#33]
It would be great if you added a QR code for the cia download.

**Comment by jtothebell** [comment]
Hi, I've never used a QR code to install a CIA before. Is it just the url of the CIA encoded in the code? Does this work?
![fake-08-0021](https://user-images.githubusercontent.com/1558589/106214348-d3ff3b80-618b-11eb-9f56-044f94c0fe97.png)

**Comment by Archonic944** [comment]
I don't have access to my 3DS right now, but I know that if you send the CIA to discord and then create a QR code based on the file link, it will work.

**Comment by jtothebell** [comment]
I just found the option in FBI and tried out this QR code, and it appeared to work. I'll add it to the releases page.
