### ISSUE TITLE
custom pause menus don't seem to work

### ISSUE THREAD

**Issue by JoleChallinor** [jtothebell/fake-08#49]
Noticed this on Run Gun Bot and PICORACER2048. Not really sure what causes the issues on the latter though.

**Comment by jtothebell** [comment]
64x64 mode is now supported. I closed the other issue I had for that, going to leave this one open as it looks like Run Gun Bot uses the new pause menu functionality added in Pico-8 v0.2.2 which is still not implemented.

**Comment by jtothebell** [comment]
Custom pause menus should be working now as of v0.0.2.16
