### ISSUE TITLE
Sugestion for an interface like splore

### ISSUE THREAD

**Issue by mtboss124** [jtothebell/fake-08#54]
Just a suggestion to add a card preview like the one in splore

**Comment by jtothebell** [comment]
Thank you for the suggestion. I agree this would be nice, and a similar suggestion has come up before. There are quite a few other bugs and compatibility improvements that need to get done before I'll be able to take a stab at it though.

**Comment by mtboss124** [comment]
Sorry i didnt know that it was alredy suggested also thanks for responding
