### ISSUE TITLE
Wii U resolution/scaling

### ISSUE THREAD

**Issue by vaguerant** [jtothebell/fake-08#57]
If you press the R button to toggle between scales on Wii U, FAKE-08 seems to get stuck in a "toggling scales" state, so that every single frame after that, the scaling changes, making it unusable and probably a health hazard for anybody with photosensitive epilepsy. The issue is only resolved by completely exiting and restarting the app.

Separately from the actual bug, if the scaling worked it could probably be somewhat better, given the multi-screen, multi-resolution setup of the Wii U. I'm not sure what the exact limitations of working with the Wii U SDL2 port are, but my understanding is that it only supports 720p. The real ideal would be not dealing with that limitation at all, so that you could have native resolution output at all resolutions, but that falls beyond the scope of a FAKE-08 issue.

That said, I wonder if it could be handled better within those limitations? Currently, the 720p output of FAKE-08 is being scaled with nearest-neighbor (no interpolation) to the output resolution: 480p on the GamePad, and any of 480p, 720p and 1080p on the TV. This is resulting in uneven pixel shapes on the GamePad and on TV for any users set to 480p or 1080p; only 720p on TV really looks correct. If it's possible with SDL2 on Wii U, the final scale for output should be performed with bilinear filtering, preserving the correct pixel shapes on both TV and GamePad regardless of resolution, in exchange for some mild blurring at pixel edges.

**Comment by jtothebell** [comment]
Oh wow, that is bad. I will see if I can the flashing fixed today. The resolution/scaling is another bag of worms. I've been meaning to see if I could change the resolution, but I see your conversation in the 4TU discord a couple weeks ago. Might have to convert it away from SDL rendering (or provide fix the Wii U's sdl port?) to solve that problem

**Comment by jtothebell** [comment]
OK, the flickering should be fixed now. I replaced the bad Wii U binary in the latest release with a patched one.

**Comment by jtothebell** [comment]
Updated title now that hitting R isn't a health hazard.
