### ISSUE TITLE
Multicart support

### ISSUE THREAD

**Issue by jtothebell** [jtothebell/fake-08#58]
`load` and `reload` with a cart file name are not yet supported. These are needed for multi cart games

**Comment by eisnerguy1** [comment]
Would love support for this so I can run the [POOM](https://freds72.itch.io/poom) standalone version on my N3DS.

**Comment by eisnerguy1** [comment]
I was wondering if there's any updates on Multicart support? Thanks!

**Comment by jtothebell** [comment]
Basic "bring-your-own-cart"* multicart support is in the app now (maybe I need to close this issue?). Last I tried POOM the title screen loaded, and I was able to choose a level, but then once the level loaded there were graphical issues (I think unrelated to multicart) that made it unplayable. 

*there is no automatic cart downloading as Pico-8 proper has, so for any multicart games, all carts have to be downloaded and placed in the cart directory ahead of time.

**Comment by eisnerguy1** [comment]
Oh dang :D It's been awhile since i've actually tried fake-08 on my N3DS. I'll give the most recent release a go and try POOM & Virtua Racing Demake.

**Comment by jtothebell** [comment]
Actually I just went and checked, and neither of those games load into actual gameplay anymore 😬 It looks like there must have been some regression I will have to hunt down.

**Comment by eisnerguy1** [comment]
Oh dang :( Ah well, I've got plenty on my N3DS to keep me busy for now :)

**Comment by jtothebell** [comment]
Latest release should address this, and Poom and Virtua racing should both work. Still no auto downloading carts, but multi cart standalone games should be fine.

**Comment by guighub** [comment]
Is this fixed? I'm working on a port to the Wii and GameCube and multicart games like Celeste 2: Lani's Trek don't seem to load properly, and often have mismatched or missing graphics and audio. Is this a problem anyone else is having on other platforms?
