### ISSUE TITLE
Remember screen size setting.

### ISSUE THREAD

**Issue by megabitsenmzq** [jtothebell/fake-08#73]
The default screen size looks weird on 3DS. I won't need to change it every time if the setting can be remembered.
![IMG_3774](https://user-images.githubusercontent.com/5499507/117284342-aec44c80-aea1-11eb-9a46-683a74f21793.jpg)

**Comment by jtothebell** [comment]
Remembering the screen size was added to version v0.0.2.6. It looks like you're running one version older than that. The current version is v0.0.2.9, so you just need to go get the latest release from the releases page.
