### ISSUE TITLE
Create loader for custom bubbles

### ISSUE THREAD

**Issue by DRok17** [jtothebell/fake-08#76]
Can you create a loader for adding custom bubbles to the live area? Retroarch and DaedalusX64 both have this, and this would make it easier to create bubbles for specific games instead of having to sort thru the list.

**Comment by Dazman100** [comment]
I would also love to be able to have custom bubbles per game.

**Comment by jtothebell** [comment]
@DRok17 I just published a release to FAKE-08 that should allow making custom bubbles. I checked what DaedalusX64 did and followed its example. The launcher code is at https://github.com/jtothebell/fake-08-vita-launcher (has a GPL license, so can't add to this repo). I've only tested one cart, but it seemed to work. I could maybe take a stab at updating RetroBuilder as well, unless you want to.

**Comment by DRok17** [comment]
Awesome, I'll check it out later tonight and let you know if I can add to RB. Thanks!

**Comment by Dazman100** [comment]
This is great thanks.



Sent from my Galaxy



-------- Original message --------
From: Jon Bell ***@***.***>
Date: 05/07/2021 15:31 (GMT+00:00)
To: jtothebell/fake-08 ***@***.***>
Cc: Dazman100 ***@***.***>, Comment ***@***.***>
Subject: Re: [jtothebell/fake-08] Create loader for custom bubbles (#76)


@DRok17<https://github.com/DRok17> I just published a release to FAKE-08 that should allow making custom bubbles. I checked what DaedalusX64 did and followed its example. The launcher code is at https://github.com/jtothebell/fake-08-vita-launcher (has a GPL license, so can't add to this repo). I've only tested one cart, but it seemed to work. I could maybe take a stab at updating RetroBuilder as well, unless you want to.

**Comment by Dazman100** [comment]
Please let me know when a builder it out.


Sent from my Galaxy



-------- Original message --------
From: DRok17 ***@***.***>
Date: 05/07/2021 15:33 (GMT+00:00)
To: jtothebell/fake-08 ***@***.***>
Cc: Dazman100 ***@***.***>, Comment ***@***.***>
Subject: Re: [jtothebell/fake-08] Create loader for custom bubbles (#76)


Awesome, I'll check it out later tonight and let you know if I can add to RB. Thanks!

**Comment by jtothebell** [comment]
The builder in the launcher repo should work now, but it's not nearly as easy as RetroBuilder. I think RB should be able to be updated to make it much easier.

**Comment by DRok17** [comment]
@jtothebell I'm not able to build a success bubble and keep getting "No lua to load" errors. Mind sending me a working one to compare?

**Comment by jtothebell** [comment]
github won't let me attach a vpk, so this one is zipped. This is for Masters of the Universe. the cart name is "motu-5.p8.png" (gets written to args.txt) and the cart needs to be in `ux0:/p8carts/`. I've started building support for absolute paths if its somewhere else, but I haven't tried it with the launcher

[MOTU.zip](https://github.com/jtothebell/fake-08/files/6766520/MOTU.zip)

**Comment by DRok17** [comment]
Ah, ic. Has to be ux0:/ and not ux0:

Got it working now with a few carts. I modified my ScummVM-Builder to work with your eboot and rom path, seems to work fine as a standalone.

https://github.com/DRok17/Fake08-Builder

Getting this to work on RB will take more time tho, there's a bunch of fixes I need to push and test out before any further releases. Adding this will be pretty simple tho.

**Comment by Dazman100** [comment]
Just made a bubble using your launcher code. Copied 3 pics to assets folder and entered details in builder. VPK installed and worked great.

I will make bubbles for all my pico roms.

Great work. Many thanks.

**Comment by DRok17** [comment]
So this looks resolved, I'll keep working on adding this to RB or possibly rolling all my builders into one app.

Thanks for the hard work on this!
