### ISSUE TITLE
 error: 'fix32' has not been declared

### ISSUE THREAD

**Issue by tropius747** [jtothebell/fake-08#78]
error: 'fix32' has not been declared 

when trying to compile, i might have messed something else up but i just wanted to check

**Comment by jtothebell** [comment]
That sounds like you need to clone the submodules. fix32 is declared in the z8lua submodule.

`git clone --recurse-submodules https://github.com/jtothebell/fake-08.git`

**Comment by tropius747** [comment]
0 [main] make (232) C:\devkitPro\msys2\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180347408/0x180352408.
                       This problem is probably due to using incompatible versions of the cygwin DLL.
                                                                                                     Search for cygwin1.dll using the Windows Start->Find/Search facility
                                                      and delete all but the most recent version.  The most recent version *should*
                reside in x:\cygwin\bin, where 'x' is the drive on which you have
                                                                                 installed the cygwin distribution.  Rebooting is also suggested if you
                                    are unable to find another cygwin DLL.

**Comment by tropius747** [comment]
0 [main] make (6948) C:\devkitPro\msys2\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180347408/0x180352408.
                                                           This problem is probably due to using incompatible versions of the cygwin DLL.
                                                         Search for cygwin1.dll using the Windows Start->Find/Search facility
                                             and delete all but the most recent version.  The most recent version *should*
                                          reside in x:\cygwin\bin, where 'x' is the drive on which you have
                           installed the cygwin distribution.  Rebooting is also suggested if you
                 are unable to find another cygwin DLL.

i have rebooted multiple times but i keep getting the same error, and i have no conflicting versions
i am running in git otherwise i get the original error i posted here
any ideas?

**Comment by jtothebell** [comment]
I'm not an expert in devkitpro windows installations, but that sounds like maybe you're using the wrong terminal. Are you using the msys2 installation that was installed with the dkp installer? and are you able to build any of the sample apps?

**Comment by jtothebell** [comment]
closing this since it appears to be an environment issue. CI builds are working as expected
