### ISSUE TITLE
video (gif) recording seems unimplemented?

### ISSUE THREAD

**Issue by ghost** [jtothebell/fake-08#84]
using [a cart](https://packbat.itch.io/rain-gif) that calls extcmd("video") to save a gif file. normally this would save to desktop, but this appears to do nothing in fake-08, on our old 3ds

**Comment by jtothebell** [comment]
That is correct, gif recording has not been implemented yet. That is a feature I consider to be lower priority than anything affecting gameplay, so I will probably not have time work on it in the near future unfortunately.
