### ISSUE TITLE
Off tempo music in rhythmfrog.p8

### ISSUE THREAD

**Issue by DPS2004** [jtothebell/fake-08#89]
[(link to game)](https://github.com/7thbeatgames/rhythm-frog)

I suspect that the cause of this is that fake-08 is ignoring the nonstandard lengths of the sounds, but I could be wrong.

![image](https://user-images.githubusercontent.com/10176105/136677356-6554b4f3-eed7-47cb-9eaf-3d74bc93ba3a.png)

**Comment by jtothebell** [comment]
Thanks for the report. I will take a closer look when I can, but life is a little hectic right now so I can't promise when that will be.

**Comment by DPS2004** [comment]
no problem, thanks for all you do on this project!
