### ISSUE TITLE
Sound for switch

### ISSUE THREAD

**Issue by jtothebell** [jtothebell/fake-08#9]

**Comment by Pyrofoux** [comment]
You mentioned in the README that you couldn't use your Switch at the moment for debugging purposes. This [Switch emulator](https://yuzu-emu.org/) might interest you, maybe you could use to it to quickly debug on a local PC?
Anyway I love your project and can't wait to see more!

**Comment by jtothebell** [comment]
Sound is working now as of release v0.0.2.3
