### ISSUE TITLE
Freeze upon attempt to exit/suspend

### ISSUE THREAD

**Issue by wesmo** [jtothebell/fake-08#90]
Device: Powkiddy V90 running Miyoo CFW 1.3.3
Version: fake-08 0.0.2.13

Issue: When pressing either the start-select button combination or suspend screen button in-game (rom already loaded and playing) the emulator freezes. Only solution is to switch v90 off and on again.

**Comment by jtothebell** [comment]
Thanks for reporting this. I've experienced intermittent freezing when exiting the emulator, but it sounds like this is every time if you suspend? Also, what is the start+select button combination supposed to do? Is that also suspend?

**Comment by wesmo** [comment]
Sorry i should've been more detailed:

1 - the start-select combo is bound by gmenu2x to take a screenshot
2 - the button that is used to suspend (located directly under the screen
between the dpad and x button on the p90) is used to suspend the screen
from gmenu2x in the miyoo cfw.
In most emulators I have tested (pcsx-rearmed, gambatte dms, gp2x,
smsplusgx) this button is the screen that brings up the emulator's option
screen and allows you to select exit.
3 - The issue seems intermittent. Sometimes when I press the suspend button
the fake-08 menu prompt comes up fine and allows me to select exit. Other
times the emulator just freezes. I've experienced this behaviour in-game
with the following cartridges: original celeste, picoracer-2048, waverace
legend and picofox.

**Comment by jtothebell** [comment]
I've finally started looking in to this some more, and it looks like it has something to do with the callback that fills the audio buffer. I've tried a couple things that seem to help, but I still saw infrequent freezes. If you are still around and would like to check it out, I'm attaching that build here

[FAKE08-bittboy-less-freezy.zip](https://github.com/jtothebell/fake-08/files/7812101/FAKE08-bittboy-less-freezy.zip)

**Comment by jtothebell** [comment]
Pretty sure I found the actual problem and have a fix. I can't get it to crash any more with this buil
[FAKE08-crash-on-exit-fix.zip](https://github.com/jtothebell/fake-08/files/7834314/FAKE08-crash-on-exit-fix.zip)
d

**Comment by jtothebell** [comment]
Newest release includes this fix. Closing.
