### ISSUE TITLE
3DS: Error loading cart LUA on Slipways

### ISSUE THREAD

**Issue by TheTrashMan-Ricky** [jtothebell/fake-08#91]
Basically what the title says. When attempting to run Slipways on 3ds, the following message happends

**Comment by jtothebell** [comment]
This is a known issue (see https://github.com/jtothebell/fake-08/wiki/Cart-Compatibility). It should be playable with the attached mod however (which just breaks out the compound `-=` operator to be a normal assignment
[slipways_p8_mod.p8.zip](https://github.com/jtothebell/fake-08/files/7559442/slipways_p8_mod.p8.zip)
)

**Comment by jtothebell** [comment]
PICO-8's lua has been updated and its behavior now matches FAKE-08. Slipways has been updated with a version that doesn't have this issue. Closing this issue.
