### ISSUE TITLE
Im stupid and dont know how to add carts

### ISSUE THREAD

**Issue by CactusBoy3** [jtothebell/fake-08#93]
how the hell do i add a cart onto it?

**Comment by jtothebell** [comment]
It varies a little bit by platform, but directions are in the readme:

For 3DS, Switch, Wii U, and Vita:

> Pico 8 cart files go in the p8carts/ directory of your memory card (SD card on 3DS, Switch, and Wii U, memory card at ux0:/ on Vita). .p8 text file carts and .p8.png image file carts are supported.

For bittboy consoles:

> Place your cart files in roms/pico-8/ and use the front end of choice to launch games. Press the menu button to return to the menu (though you can also press start and exit to the FAKE-08 bios menu if you would like).

**Comment by CactusBoy3** [comment]
How do I get the .p8 files tho

**Comment by jtothebell** [comment]
From the readme:

> Carts
> 
> You browse and download carts by using the SPLORE() function in Pico 8 (again, if you have $15 to spend, and you are interested in game dev, it is well worth your money). Once you have loaded a cart that you want to try on FAKE-08, type save {{cartname}}.p8 to save the cart as a text file, then copy that file to your device's SD card.
> 
> You can also browse carts on the Pico-8 BBS website, but can only download complete carts in png format. As of pre release v0.0.1.1 Fake-08 should load and play png carts provided they don't use any other unsupported features. You can download p8.png carts from the Cart link in the lower left of the game view, and save it into your p8carts directory.
> 
> If you are trying to play a multi cart game, it should be noted that you must provide all the carts required by the game as FAKE-08 currently does not have cart downloading capabilities. All carts should be placed in the same directory.

the Pico 8 BBS is here: https://www.lexaloffle.com/bbs/?cat=7

here is a screenshot pointing to the cart link referenced:
![image](https://user-images.githubusercontent.com/1558589/147164915-744b9d36-90da-4ae9-a5d3-592ec7365c7a.png)

**Comment by CactusBoy3** [comment]
Ok thanks for the help 😃😃😃
